### ISSUE TITLE
Fresh install with original hardware（wifi）

### ISSUE THREAD

**Issue by Carnia** [osy/HaC-Mini#1019]
hello 

I want to do a fresh install of macOS (monterey12.6) to nuc8i7hvk, I didn't replace the original NIC (because I don't need the airdrop feature).

So I'm going to do this:

1. Creating OSX Installer with a USB flash drive (monterey12.6)
2. Insert the USB flash drive and install macOS to the hard disk
3. Enter the system

According to the tutorial (https://osy.gitbook.io/hac-mini-guide/installation-guide/installation), I did not use HacMini.pkg to Patching OSX Installer (USB flash drive) before installing the system. 
**But now I have a question, after the installation, how can I download HacMini.pkg without any driver adaptation? (Because I can't connect to wifi at this time, and I guess the system can't recognize the U disk I plugged in，is that right？ )**

**Comment by Medizinmann-MD** [comment]
You could of course put the HacMini.pkg on an USB-Stick - why not.

But you need to install Xcode in order to work and this won't work without Network.
But Intel WiFi should work with Monterey and you can always use a Cable Connection on LAN1.

But I would strongly recommend getting a Broadcom WiFi/Bluetooth card (i.e. one with BCM94360NG) for around $30-$40 - this makes the life with you Hack so very much easier!

**Comment by Medizinmann-MD** [comment]
LAN1 always worked and even LAN2 works with the fix in the latest pre-release 3.2.0 (see https://github.com/osy/HaC-Mini/issues/947).
