### ISSUE TITLE
Description of packages in installer not working

### ISSUE THREAD

**Issue by topiga** [osy/HaC-Mini#1080]
**Describe the bug**
Description of options are not working properly

**Environment:**
 - Running OSX version: 13.2.1
 - Target drive OSX version: 13.2.1
 - HaC Mini installer version: Built from source (abbe355f616c20f6e5c3bbf97caff916b9a286c7)

**Photos**
![image](https://user-images.githubusercontent.com/38886040/232105186-5b7ceba6-382b-4f83-b76e-8a746c67adcc.png)

**Comment by osy** [comment]
Which description is not working? Can you try https://github.com/osy/HaC-Mini/suites/12244416113/artifacts/647881036

**Comment by topiga** [comment]
The titles of certain packages. The result is the same with the version you provided

**Comment by osy** [comment]
Are you sure the issue isn’t with your translation being incomplete? Have you looked at it in Packages editor?

**Comment by SashonIT** [comment]
Hello dear folks.
I need to clarify something in the case of Antelope Audio Interface via Thunderbolt 3 on Hades Canyon.

I had to reinstall 13.3.1 yesterday.
After adding DMAR.aml and DMAC.aml to the config.plist, there must still be the following entry.




<img width="813" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/126977959/232327251-ca5ab551-f926-4bab-85c0-695e89710fc5.png">

It is now the case that DisableIOmapper and DisableIOmapping must both be deactivated so that the Antelope can later be recognised by its own software.

Only then can you install the Antelope drivers and then it will run smoothly.


With DiableIomapper / mapping activated

The Antelope is visible in the system and under IOReg.

But the Antelope software absolutely requires that Apple VTD is on.

<img width="739" alt="AppleVTD_IOREG" src="https://user-images.githubusercontent.com/126977959/232327326-ce9a4938-5351-4f0b-9a62-7f2a11a1d79a.png">


See picture.


This is not the case when Diasble IOmapper is activated.

Just as a hint.

Translated with www.DeepL.com/Translator (free version)

**Comment by topiga** [comment]
Okay, I’ll do a PR. Thanks for the hint !

**Comment by osy** [comment]
@SashonIT you shouldn’t need to add DMAR/DMAC with the latest HacMini+OpenCore. Can you see AppleVTD without adding it?

**Comment by topiga** [comment]
> But the Antelope software absolutely requires that Apple VTD is on.
> 
> This is not the case when Diasble IOmapper is activated.

I think that’s exactly what he is saying.

**Comment by osy** [comment]
@SashonIT Can you please try https://github.com/osy/HaC-Mini/suites/12271522482/artifacts/649826905

**Comment by SashonIT** [comment]
@topiga , @osy  Thanks for your Replies in this Case.

Today i am fully busy.

I can/ will try it  tommorow.

I have now an Extra Partition for Test Purposes and Future Ventura updates / playing arround with the Ventura Betas.

I will try it there.

I keep you updated tomorrow.

**Comment by SashonIT** [comment]
> @SashonIT Can you please try https://github.com/osy/HaC-Mini/suites/12271522482/artifacts/649826905

I could try it today.....

I only saw it as u wrote it to me..... That there is a 3.30 Version.

Its running Seamlessly.

Its now a One Take Install Process.

Antelope is also runnin.

:-x

Big Thanks to you all.

That means a lot to me.

**Comment by osy** [comment]
@SashonIT have you tested on macOS 13.3?

**Comment by SashonIT** [comment]
@osy —-> Oh sorry …. i forgot to write on which Version i installed the HacMini 3.30 Installer.

I installed Ventura 13.3.1 Never Tested 13.3.

Only 3 weeks ago, when the Grafic Problems came up. —-> I used OpenCore Efi self Configured .

Do you need a proof for MacOS Version 13.3 as well?

For me i thought its not necessary to go with 13.3, when 13.3.1 is Out.

Tell me if you need a Approval Test for Version 13.3 .

Then i will do it.

But not today. Tomorrow i have time for this.

**Comment by osy** [comment]
13.3.1 is good
