### ISSUE TITLE
I can't install HaC-Mini

### ISSUE THREAD

**Issue by JerryXu-code** [osy/HaC-Mini#396]
- Running OSX version: 11.0.1 beta
 - Target drive OSX version: 11.0.1 beta
 - HaC Mini installer version: v2.14

I can't install it.
[log.txt](https://github.com/osy86/HaC-Mini/files/5589257/log.txt)

**Comment by cuteluo1983** [comment]
> * Running OSX version: 11.0.1 beta
> * Target drive OSX version: 11.0.1 beta
> * HaC Mini installer version: v2.14
> 
> I can't install it.
> [log.txt](https://github.com/osy86/HaC-Mini/files/5589257/log.txt)

参照教程，全新安装推荐，直接升级遇到问题的几率很大
另外，pkg文件怎么样会无法安装呢，我表示疑惑的很

**Comment by CyberBlaed** [comment]
- 
-     Running OSX version: 10.15.7
-     Target drive OSX version: 10.15.7
-     HaC Mini installer version: v2.14

Installer will get upto patching my USB and then (!) Fail.
(This is all in a VM made myself due to the only Mac I have is Sierra, which also gives the same issues)

PDF of full log attached.
[Google Drive PDF](https://drive.google.com/file/d/1ep3gsOvmOiCxJka5779hRoFUjymjaS0-/view?usp=sharing)

TXT Version
[PasteBin Version](https://pastebin.com/64q3RPDe)

ATM I am unable to diagnose the issue further regardless of what i try, I attempted Hac Mini 2.13 as a gamble (Fresh USB ofcourse) and that failed too on patching. so, I Don't know what else to try or do at this stage.

**Comment by osy** [comment]
@JerryXu-code From your log: `ERROR: can't mount ESP partition (disk0s1) ! Check that the partition is well formated in HFS or Fat32.` This means your drive is not formatted properly: https://osy.gitbook.io/hac-mini-guide/installation-guide/installation#creating-osx-installer

@CyberBlaed From your log: `Partition is FDisk_partition_scheme, not GUID_partition_scheme!` This means your drive is not formatted properly: https://osy.gitbook.io/hac-mini-guide/installation-guide/installation#creating-osx-installer
